### ISSUE TITLE
bug on nightly

### ISSUE THREAD

**Issue by richardanaya** [bastion-rs/agnostik#9]
i'm a bit unsure if this is a temporary nightly issue, or something for us to be aware of coming up. Anyhow, thought i'd like people know.

error[E0596]: cannot borrow data in a dereference of `core::pin::Pin<&mut join_handle::JoinHandle<R>>` as mutable
##[error]  --> src/join_handle.rs:54:39

**Comment by vertexclique** [comment]
Thanks Richard, we will take a look at this.

**Comment by o0Ignition0o** [comment]
Hey there :)

I'm running on nightly and can't reproduce it (today ? ^^)

Could you please let me know if the issue can be closed?

Thanks :)

**Comment by richardanaya** [comment]
Sounds good!
